name: Hotel Booking System Using MERN Stack Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install backend dependencies
        run: |
          cd Backend/back
          npm install
          npm audit fix --force
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Heroku (Backend)
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  frontend-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install npx if not already installed
        run: command -v npx || npm install -g npx

      - name: Deploy to Vercel (Frontend)
        run: npx vercel --prod -t ${{secrets.VERCEL_TOKEN}} -m githubCommitSha=32e6cd17bd2a09b0bb7fa748be1be7c8bee260bb -m githubCommitAuthorName=shakeeb2001 -m githubCommitAuthorLogin=shakeeb2001 -m githubDeployment=1 -m githubOrg=shakeeb2001 -m githubRepo=Final-Full-Stack-Project -m githubCommitOrg=shakeeb2001 -m githubCommitRepo=Final-Full-Stack-Project -m githubCommitMessage="Update cicd.yml" -m githubCommitRef=main
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
          working-directory: front
